FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o publisher ./cmd/publisher

FROM alpine
WORKDIR /app
COPY --from=builder /app/publisher .
CMD ["./publisher"]
